---

- name: collect MikroTik facts
  hosts: mikrotik_routers
  gather_facts: no
  connection: local

  tasks:

  - name: gather facts from routers
    mikrotik_facts:
      hostname: "{{ inventory_hostname }}"
      username: admin
      verbose: yes
    register: mikrotik

  - debug:
      var: mikrotik
