---

- name: Upgrade MikroTik routers
  hosts: mikrotik_routers
  gather_facts: no
  connection: local
  #serial: 1

  vars_files:
    - routeros/versions.yml

  tasks:

  - debug:
      var: routeros_current
    run_once: yes

  - name: upgrade and reboot
    mikrotik_package:
      hostname: "{{ inventory_hostname }}"
      username: admin
      version: "{{ routeros_current }}"
      packages:
        - system
        - security
        - dhcp
        - advanced-tools
      reboot: true
    register: result

  - debug:
      var: result
